server.port=8081

server.address=0.0.0.0

spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
# Allow H2 console to be shown in a frame (needed for mini-apps/proxies)
spring.h2.console.settings.web-allow-others=true
